[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '/(?:\.git|\.venv|node_modules|build|dist|__pycache__)/'

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip_glob = [
    "*/.venv/*",
    "*/node_modules/*",
    "*/build/*",
    "*/dist/*",
    "*/__pycache__/*",
]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503", "E501"]
exclude = [
    ".git",
    ".venv",
    "node_modules",
    "build",
    "dist",
    "__pycache__",
]

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = [
    "shared/auth/tests/",
    "shared/database_base/tests/",
]